-- MySQL Script generated by MySQL Workbench
-- Thu Nov 18 02:09:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cino_cms
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cino_cms` ;

-- -----------------------------------------------------
-- Schema cino_cms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cino_cms` DEFAULT CHARACTER SET utf8 ;
USE `cino_cms` ;

-- -----------------------------------------------------
-- Table `cino_cms`.`movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`movies` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`movies` (
  `id_movie` INT NOT NULL SERIAL,
  `name` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `path_to_main_image` VARCHAR(255) NOT NULL,
  `trailer_link` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_movie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`cafes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`cafes` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`cafes` (
  `id_cafe` INT NOT NULL SERIAL,
  `name` NVARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `path_to_main_image` NVARCHAR(255) NULL,
  `enabled` BIT NOT NULL,
  `creation_date` DATE NOT NULL,
  PRIMARY KEY (`id_cafe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`cinemas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`cinemas` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`cinemas` (
  `id_cinema` INT NOT NULL SERIAL,
  `name` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `conditions` MEDIUMTEXT NOT NULL,
  `path_to_logo` VARCHAR(255) NOT NULL,
  `path_to_top_banner` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_cinema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`languages` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`languages` (
  `id_language` INT NOT NULL SERIAL,
  `language` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_language`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`genders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`genders` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`genders` (
  `id_gender` INT NOT NULL SERIAL,
  `gender` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_gender`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`cities` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`cities` (
  `id_city` INT NOT NULL SERIAL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_city`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`authorizations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`authorizations` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`authorizations` (
  `id_authorization` INT NOT NULL SERIAL,
  `e_mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_authorization`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`users` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`users` (
  `id_user` INT NOT NULL SERIAL,
  `language_fk` INT NOT NULL,
  `gender_fk` INT NOT NULL,
  `city_fk` INT NOT NULL,
  `authorization_fk` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `second_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `number_bank_card` INT NOT NULL,
  `number_phone` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `registration_date` DATE NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `user_language_fk_idx` (`language_fk` ASC) VISIBLE,
  INDEX `user_gender_fk_idx` (`gender_fk` ASC) VISIBLE,
  INDEX `user_city_fk_idx` (`city_fk` ASC) VISIBLE,
  INDEX `user_authorization_fk_idx` (`authorization_fk` ASC) VISIBLE,
  CONSTRAINT `user_language_fk`
    FOREIGN KEY (`language_fk`)
    REFERENCES `cino_cms`.`languages` (`id_language`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `user_gender_fk`
    FOREIGN KEY (`gender_fk`)
    REFERENCES `cino_cms`.`genders` (`id_gender`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `user_city_fk`
    FOREIGN KEY (`city_fk`)
    REFERENCES `cino_cms`.`cities` (`id_city`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `user_authorization_fk`
    FOREIGN KEY (`authorization_fk`)
    REFERENCES `cino_cms`.`authorizations` (`id_authorization`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`admins` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`admins` (
  `id_admin` INT NOT NULL SERIAL,
  `authorization_fk` INT NOT NULL,
  PRIMARY KEY (`id_admin`),
  INDEX `authorization_idx` (`authorization_fk` ASC) VISIBLE,
  CONSTRAINT `authorization_admin_fk`
    FOREIGN KEY (`authorization_fk`)
    REFERENCES `cino_cms`.`authorizations` (`id_authorization`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`movies_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`movies_types` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`movies_types` (
  `id_type` INT NOT NULL SERIAL,
  `movie_fk` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_type`),
  INDEX `movie_idx` (`movie_fk` ASC) VISIBLE,
  CONSTRAINT `movie_types_fk`
    FOREIGN KEY (`movie_fk`)
    REFERENCES `cino_cms`.`movies` (`id_movie`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`halls`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`halls` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`halls` (
  `id_hall` INT NOT NULL SERIAL,
  `cinema_fk` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `path_to_hall_layout` VARCHAR(255) NOT NULL,
  `path_to_top_banner` VARCHAR(255) NOT NULL,
  `creation_date` DATE NOT NULL,
  PRIMARY KEY (`id_hall`),
  INDEX `halls_cinema_fk_idx` (`cinema_fk` ASC) VISIBLE,
  CONSTRAINT `halls_cinema_fk`
    FOREIGN KEY (`cinema_fk`)
    REFERENCES `cino_cms`.`cinemas` (`id_cinema`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`news` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`news` (
  `id_news` INT NOT NULL SERIAL,
  `name` VARCHAR(100) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `publication_date` DATE NOT NULL,
  `creation_date` DATE NOT NULL,
  `path_to_main_image` VARCHAR(255) NOT NULL,
  `link_to_video` VARCHAR(255) NOT NULL,
  `enabled` BIT NOT NULL,
  PRIMARY KEY (`id_news`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`schedules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`schedules` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`schedules` (
  `id_schedule` INT NOT NULL SERIAL,
  `movie_fk` INT NOT NULL,
  `hall_fk` INT NOT NULL,
  `time` TIME NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id_schedule`),
  INDEX `movie_idx` (`movie_fk` ASC) VISIBLE,
  INDEX `hall_idx` (`hall_fk` ASC) VISIBLE,
  CONSTRAINT `movie_schedules_fk`
    FOREIGN KEY (`movie_fk`)
    REFERENCES `cino_cms`.`movies` (`id_movie`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `hall_schedules_fk`
    FOREIGN KEY (`hall_fk`)
    REFERENCES `cino_cms`.`halls` (`id_hall`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`deals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`deals` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`deals` (
  `id_deal` INT NOT NULL SERIAL,
  `name` VARCHAR(100) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `publication_date` DATE NOT NULL,
  `creation_date` DATE NOT NULL,
  `path_to_main_image` VARCHAR(255) NOT NULL,
  `link_to_video` VARCHAR(255) NOT NULL,
  `enabled` BIT NOT NULL,
  PRIMARY KEY (`id_deal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`vip_halls`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`vip_halls` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`vip_halls` (
  `id_vip_hall` INT NOT NULL SERIAL,
  `name` VARCHAR(100) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `path_to_main_image` VARCHAR(255) NULL,
  `enabled` BIT NOT NULL,
  `creation_date` DATE NOT NULL,
  PRIMARY KEY (`id_vip_hall`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`childrens_rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`childrens_rooms` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`childrens_rooms` (
  `id_childrens_room` INT NOT NULL SERIAL,
  `name` VARCHAR(100) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `path_to_main_image` VARCHAR(255) NULL,
  `enabled` BIT NOT NULL,
  `creation_date` DATE NOT NULL,
  PRIMARY KEY (`id_childrens_room`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`advertisements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`advertisements` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`advertisements` (
  `id_advertisement` INT NOT NULL SERIAL,
  `name` VARCHAR(100) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `path_to_main_image` VARCHAR(255) NULL,
  `enabled` BIT NOT NULL,
  `creation_date` DATE NOT NULL,
  PRIMARY KEY (`id_advertisement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`contacts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`contacts` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`contacts` (
  `id_contact` INT NOT NULL SERIAL,
  `name` VARCHAR(45) NOT NULL,
  `creation_date` DATE NOT NULL,
  `enabled` BIT NOT NULL,
  PRIMARY KEY (`id_contact`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`contacts_information`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`contacts_information` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`contacts_information` (
  `id_contact` INT NOT NULL SERIAL,
  `contact_fk` INT NOT NULL,
  `name_cinema` VARCHAR(45) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `coordinates_for_the_map` VARCHAR(100) NOT NULL,
  `path_to_logo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_contact`),
  INDEX `contact_information_contact_fk_idx` (`contact_fk` ASC) VISIBLE,
  CONSTRAINT `contact_information_contact_fk`
    FOREIGN KEY (`contact_fk`)
    REFERENCES `cino_cms`.`contacts` (`id_contact`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`movies_galleries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`movies_galleries` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`movies_galleries` (
  `id_movies_gallery` INT NOT NULL SERIAL,
  `movie_fk` INT NOT NULL,
  `path_to_image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_movies_gallery`),
  INDEX `MoviesImage_idx` (`movie_fk` ASC) VISIBLE,
  CONSTRAINT `movies_image_fk`
    FOREIGN KEY (`movie_fk`)
    REFERENCES `cino_cms`.`movies` (`id_movie`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`cinemas_galleries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`cinemas_galleries` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`cinemas_galleries` (
  `id_cinemas_image` INT NOT NULL SERIAL,
  `cinema_fk` INT NOT NULL,
  `path_to_image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_cinemas_image`),
  INDEX `CinemasImage_idx` (`cinema_fk` ASC) VISIBLE,
  CONSTRAINT `cinemas_gallery_fk`
    FOREIGN KEY (`cinema_fk`)
    REFERENCES `cino_cms`.`cinemas` (`id_cinema`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`halls_galleries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`halls_galleries` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`halls_galleries` (
  `id_halls_gallery` INT NOT NULL SERIAL,
  `hall_fk` INT NOT NULL,
  `path_to_image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_halls_gallery`),
  INDEX `HallsImage_idx` (`hall_fk` ASC) VISIBLE,
  CONSTRAINT `halls_image_fk`
    FOREIGN KEY (`hall_fk`)
    REFERENCES `cino_cms`.`halls` (`id_hall`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`deals_galleries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`deals_galleries` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`deals_galleries` (
  `id_deals_gallery` INT NOT NULL SERIAL,
  `deal_fk` INT NOT NULL,
  `path_to_image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_deals_gallery`),
  INDEX `DealHalleryFK_idx` (`deal_fk` ASC) VISIBLE,
  CONSTRAINT `deal_gallery_fk`
    FOREIGN KEY (`deal_fk`)
    REFERENCES `cino_cms`.`deals` (`id_deal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`childrens_rooms_galleries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`childrens_rooms_galleries` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`childrens_rooms_galleries` (
  `id_childrens_rooms_gallery` INT NOT NULL SERIAL,
  `childrens_room_fk` INT NOT NULL,
  `path_to_image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_childrens_rooms_gallery`),
  INDEX `ChildrensRoomGalleriesFK_idx` (`childrens_room_fk` ASC) VISIBLE,
  CONSTRAINT `childrens_rooms_galleries_fk`
    FOREIGN KEY (`childrens_room_fk`)
    REFERENCES `cino_cms`.`childrens_rooms` (`id_childrens_room`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`advertisements_galleries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`advertisements_galleries` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`advertisements_galleries` (
  `id_advertisements_gallery` INT NOT NULL SERIAL,
  `advertisement_fk` INT NOT NULL,
  `path_to_image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_advertisements_gallery`),
  INDEX `AdvertisementsGalleriesFK_idx` (`advertisement_fk` ASC) VISIBLE,
  CONSTRAINT `advertisements_galleries_fk`
    FOREIGN KEY (`advertisement_fk`)
    REFERENCES `cino_cms`.`advertisements` (`id_advertisement`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`vip_halls_galleries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`vip_halls_galleries` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`vip_halls_galleries` (
  `id_vip_halls_gallery` INT NOT NULL SERIAL,
  `vip_hall_fk` INT NOT NULL,
  `path_to_image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_vip_halls_gallery`),
  INDEX `VipHallesGalleriesFK_idx` (`vip_hall_fk` ASC) VISIBLE,
  CONSTRAINT `vip_halls_galleries_fk`
    FOREIGN KEY (`vip_hall_fk`)
    REFERENCES `cino_cms`.`vip_halls` (`id_vip_hall`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`news_galleries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`news_galleries` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`news_galleries` (
  `id_news_gallery` INT NOT NULL SERIAL,
  `news_fk` INT NOT NULL,
  `path_to_image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_news_gallery`),
  INDEX `NewsGalleriesFK_idx` (`news_fk` ASC) VISIBLE,
  CONSTRAINT `news_galleries_fk`
    FOREIGN KEY (`news_fk`)
    REFERENCES `cino_cms`.`news` (`id_news`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`cafes_galleries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`cafes_galleries` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`cafes_galleries` (
  `id_cafes_gallery` INT NOT NULL SERIAL,
  `cafe_fk` INT NOT NULL,
  `path_to_image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_cafes_gallery`),
  INDEX `CafesGalleriesFK_idx` (`cafe_fk` ASC) VISIBLE,
  CONSTRAINT `cafes_galleries_fk`
    FOREIGN KEY (`cafe_fk`)
    REFERENCES `cino_cms`.`cafes` (`id_cafe`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`current_movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`current_movies` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`current_movies` (
  `id_current_movie` INT NOT NULL SERIAL,
  `movie_fk` INT NOT NULL,
  PRIMARY KEY (`id_current_movie`),
  INDEX `movies_current_movies_idx` (`movie_fk` ASC) VISIBLE,
  CONSTRAINT `movies_current_movies`
    FOREIGN KEY (`movie_fk`)
    REFERENCES `cino_cms`.`movies` (`id_movie`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`future_movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`future_movies` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`future_movies` (
  `id_future_movie` INT NOT NULL SERIAL,
  `movie_fk` INT NOT NULL,
  PRIMARY KEY (`id_future_movie`),
  INDEX `movies_future_movie_idx` (`movie_fk` ASC) VISIBLE,
  CONSTRAINT `movies_future_movie`
    FOREIGN KEY (`movie_fk`)
    REFERENCES `cino_cms`.`movies` (`id_movie`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`hidden_movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`hidden_movies` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`hidden_movies` (
  `id_hidden_movie` INT NOT NULL SERIAL,
  `movie_fk` INT NOT NULL,
  PRIMARY KEY (`id_hidden_movie`),
  INDEX `movies_hidden_movies_idx` (`movie_fk` ASC) VISIBLE,
  CONSTRAINT `movies_hidden_movies`
    FOREIGN KEY (`movie_fk`)
    REFERENCES `cino_cms`.`movies` (`id_movie`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`background_banners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`background_banners` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`background_banners` (
  `id_background_banner` INT NOT NULL SERIAL,
  `path_to_background_banner` VARCHAR(255) NOT NULL,
  `enabled` BIT NOT NULL,
  PRIMARY KEY (`id_background_banner`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`top_banners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`top_banners` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`top_banners` (
  `id_top_banner` INT NOT NULL SERIAL,
  `rotation_speed` INT NOT NULL,
  `enabled` BIT NOT NULL,
  PRIMARY KEY (`id_top_banner`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`news_and_deals_banners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`news_and_deals_banners` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`news_and_deals_banners` (
  `id_news_and_deals_banner` INT NOT NULL SERIAL,
  `rotation_speed` INT NOT NULL,
  `enabled` BIT NOT NULL,
  PRIMARY KEY (`id_news_and_deals_banner`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`description_current_cinemas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`description_current_cinemas` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`description_current_cinemas` (
  `id_description_current_cinema` INT NOT NULL SERIAL,
  `name` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `path_to_main_image` VARCHAR(255) NULL,
  `enabled` BIT NOT NULL,
  `creation_date` DATE NOT NULL,
  PRIMARY KEY (`id_description_current_cinema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`description_current_cinemas_galleries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`description_current_cinemas_galleries` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`description_current_cinemas_galleries` (
  `id_description_current_cinemas_gallery` INT NOT NULL SERIAL,
  `description_current_cinema_fk` INT NOT NULL,
  `path_to_image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_description_current_cinemas_gallery`),
  INDEX `gallery_describe_current_cinema_fk_idx` (`description_current_cinema_fk` ASC) VISIBLE,
  CONSTRAINT `gallery_description_current_cinema_fk`
    FOREIGN KEY (`description_current_cinema_fk`)
    REFERENCES `cino_cms`.`description_current_cinemas` (`id_description_current_cinema`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`main_pages_information`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`main_pages_information` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`main_pages_information` (
  `id_main_page_information` INT NOT NULL SERIAL,
  `name` NVARCHAR(45) NOT NULL,
  `first_phone` VARCHAR(45) NULL,
  `second_phone` MEDIUMTEXT NULL,
  `enabled` BIT NOT NULL,
  `creation_date` DATE NOT NULL,
  PRIMARY KEY (`id_main_page_information`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`top_banners_galleries_with_information`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`top_banners_galleries_with_information` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`top_banners_galleries_with_information` (
  `id_top_banners_gallery` INT NOT NULL SERIAL,
  `top_banners_fk` INT NOT NULL,
  `url` VARCHAR(255) NULL,
  `description` MEDIUMTEXT NULL,
  `path_to_image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_top_banners_gallery`),
  INDEX `news_galleries_fk0_idx` (`top_banners_fk` ASC) VISIBLE,
  CONSTRAINT `top_banners_gallery_fk`
    FOREIGN KEY (`top_banners_fk`)
    REFERENCES `cino_cms`.`top_banners` (`id_top_banner`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`news_and_deals_banners_galleries_with_information`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`news_and_deals_banners_galleries_with_information` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`news_and_deals_banners_galleries_with_information` (
  `id_news_and_deals_banners_galleries` INT NOT NULL SERIAL,
  `news_and_deals_banners_fk` INT NOT NULL,
  `url` VARCHAR(255) NULL,
  `path_to_image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_news_and_deals_banners_galleries`),
  INDEX `background_banners_galleries_fk_idx` (`news_and_deals_banners_fk` ASC) VISIBLE,
  CONSTRAINT `background_banners_galleries_fk`
    FOREIGN KEY (`news_and_deals_banners_fk`)
    REFERENCES `cino_cms`.`news_and_deals_banners` (`id_news_and_deals_banner`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`additional_pages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`additional_pages` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`additional_pages` (
  `id_additional_page` INT NOT NULL SERIAL,
  `name` VARCHAR(100) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `path_to_main_image` VARCHAR(255) NOT NULL,
  `enabled` BIT NOT NULL,
  `creation_date` DATE NOT NULL,
  PRIMARY KEY (`id_additional_page`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`additional_pages_galleries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`additional_pages_galleries` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`additional_pages_galleries` (
  `id_additional_pages_gallery` INT NOT NULL SERIAL,
  `additional_page_fk` INT NOT NULL,
  `path_to_image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_additional_pages_gallery`),
  INDEX `additional_pages_galleries_additional_page_fk_idx` (`additional_page_fk` ASC) VISIBLE,
  CONSTRAINT `additional_pages_galleries_additional_page_fk`
    FOREIGN KEY (`additional_page_fk`)
    REFERENCES `cino_cms`.`additional_pages` (`id_additional_page`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cino_cms`.`mailings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cino_cms`.`mailings` ;

CREATE TABLE IF NOT EXISTS `cino_cms`.`mailings` (
  `id_mailing` INT NOT NULL SERIAL,
  `path_to_file` VARCHAR(255) NOT NULL,
  `original_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_mailing`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
